[package]
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2018"
name = "blub"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.3" 
cgmath = {git = "https://github.com/rustgd/cgmath", rev = "50a345b", features = ["rand", "serde"]} 
enumflags2 = "^0.6" 
env_logger = "0.7" 
futures = "0.3" 
imgui = "0.4" 
imgui-wgpu = {git = "https://github.com/Wumpf/imgui-wgpu-rs", rev = "260edd5"} 
imgui-winit-support = {version = "0.4", default-features = false, features = ["winit-20"]} 
lazy_static = "1.4" 
log = "0.4" 
more-asserts = "0.2" 
notify = "5.0.0-pre.2" 
png = "0.16" 
rand = {version = "0.7.3", features = ["small_rng"]} 
regex = "1" 
scopeguard = "1.1" 
serde = {version = "1.0", features = ["derive"]} 
serde_json = "1.0" 
shaderc = "0.6" 
strum = "0.19" 
strum_macros = "0.19" 
wgpu = {git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "c125f70"}#, features = ["trace"]}          
winit = "0.21" # Can't upgrade to 0.22 because of imgui-winit-support
